vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix: '%app.path.products_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            upload_destination: '%kernel.project_dir%/public%app.path.products_images%'
